spring:
  mvc:
    view:
      suffix: .html
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatDB

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG